name: flutter_backends
description: Sample project to demonstrate usage of various Flutter backends

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  appwrite: ^2.0.3
  cached_network_image: ^3.1.0+1
  cupertino_icons: ^1.0.4
  flutter_bloc: ^8.0.0
  flutter_slidable: ^1.1.0
  equatable: ^2.0.3
  firebase_core: ^1.10.0
  firebase_auth: ^3.2.0
  firebase_storage: ^10.1.0
  cloud_firestore: ^3.1.0
  supabase_flutter: ^0.2.9
  backend_repository:
    path: packages/backend_repository
  appwrite_repository:
    path: packages/appwrite_repository
  firebase_repository:
    path: packages/firebase_repository
  supabase_repository:
    path: packages/supabase_repository


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4

flutter:
  uses-material-design: true
  assets:
    - assets/images/
